.\" Manpage for Mermaid.
.\" Errors not found.
.SH NAME
Mermaid \- wonderful creature which calculates the area bordered by 3 functions.
.SH SYNOPSIS
Mermaid [OPTION]
.SH DESCRIPTION
Calculates the integral bordered by 3 predefined functions using rectangular method and for this finding the roots through chord method.
.SH OPTIONS
-help   Prints possible OPTIONS
-r      Calculates roots for 3 given functions and prints the results
-i      Calculates the integral and prints the result
-ri     Calculates integral and prints roots needed to calculate it and the integral
.SH SEE ALSO
To be continued ...
.SH BUGS
May contain bugs :)
.SH AUTHOR
Korolyova Juana (saidodjuana@gmail.com)